include: package:lints/recommended.yaml

analyzer:
  errors:
    unused_import: error
    unused_local_variable: error
    dead_code: error
  exclude:
    - build/**

linter:
  rules:
    always_declare_return_types: true
    avoid_dynamic_calls: true
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    no_adjacent_strings_in_list: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true
    secure_pubspec_urls: true
    unawaited_futures: true
