import 'profile.dart';
import 'scan_control.dart';

CentraProfile updateProfile(
  CentraProfile profile, {
  String? locale,
  SourceConfig? source,
  List<String>? algorithmIds,
  List<String>? includePatterns,
  List<String>? excludePatterns,
  SymlinkPolicy? symlinkPolicy,
  bool? includeHiddenFiles,
  bool? capturePermissions,
  bool? captureModificationTimes,
  int? workerCount,
  bool? failOnReadError,
  OutputConfig? output,
  VerificationMode? verificationMode,
  ReadErrorPolicy? readErrorPolicy,
  int? readRetryCount,
  int? unstableRetryCount,
  ScanLimits? limits,
  String? trustedBaselineManifest,
  String? trustedBaselineSignature,
  String? trustedPublicKey,
  String? trustedSigner,
  String? releaseCommit,
  String? releaseBuild,
  DateTime? updatedAt,
}) =>
    CentraProfile(
      id: profile.id,
      name: profile.name,
      locale: locale ?? profile.locale,
      source: source ?? profile.source,
      algorithmIds: algorithmIds ?? profile.algorithmIds,
      includePatterns: includePatterns ?? profile.includePatterns,
      excludePatterns: excludePatterns ?? profile.excludePatterns,
      customAlgorithms: profile.customAlgorithms,
      symlinkPolicy: symlinkPolicy ?? profile.symlinkPolicy,
      includeHiddenFiles: includeHiddenFiles ?? profile.includeHiddenFiles,
      capturePermissions: capturePermissions ?? profile.capturePermissions,
      captureModificationTimes:
          captureModificationTimes ?? profile.captureModificationTimes,
      workerCount: workerCount ?? profile.workerCount,
      failOnReadError: failOnReadError ?? profile.failOnReadError,
      output: output ?? profile.output,
      projectKind: profile.projectKind,
      createdAt: profile.createdAt,
      updatedAt: updatedAt ?? DateTime.now().toUtc(),
      verificationMode: verificationMode ?? profile.verificationMode,
      readErrorPolicy: readErrorPolicy ?? profile.readErrorPolicy,
      readRetryCount: readRetryCount ?? profile.readRetryCount,
      unstableRetryCount: unstableRetryCount ?? profile.unstableRetryCount,
      limits: limits ?? profile.limits,
      trustedBaselineManifest:
          trustedBaselineManifest ?? profile.trustedBaselineManifest,
      trustedBaselineSignature:
          trustedBaselineSignature ?? profile.trustedBaselineSignature,
      trustedPublicKey: trustedPublicKey ?? profile.trustedPublicKey,
      trustedSigner: trustedSigner ?? profile.trustedSigner,
      releaseCommit: releaseCommit ?? profile.releaseCommit,
      releaseBuild: releaseBuild ?? profile.releaseBuild,
    );

SourceConfig updateSourceConfig(
  SourceConfig source, {
  String? root,
  String? host,
  String? user,
  int? port,
  String? identityFile,
  SshAuthMethod? sshAuthMethod,
  SshHostKeyPolicy? sshHostKeyPolicy,
  String? hostKeyType,
  String? hostKeyFingerprint,
  int? connectTimeoutSeconds,
  int? keepAliveSeconds,
  String? sshConnectionId,
  String? sshConnectionName,
  String? container,
  String? image,
  String? service,
  String? composeFile,
  String? dockerContext,
}) =>
    SourceConfig(
      type: source.type,
      root: root ?? source.root,
      host: host ?? source.host,
      user: user ?? source.user,
      port: port ?? source.port,
      identityFile: identityFile ?? source.identityFile,
      sshAuthMethod: sshAuthMethod ?? source.sshAuthMethod,
      sshHostKeyPolicy: sshHostKeyPolicy ?? source.sshHostKeyPolicy,
      hostKeyType: hostKeyType ?? source.hostKeyType,
      hostKeyFingerprint: hostKeyFingerprint ?? source.hostKeyFingerprint,
      connectTimeoutSeconds:
          connectTimeoutSeconds ?? source.connectTimeoutSeconds,
      keepAliveSeconds: keepAliveSeconds ?? source.keepAliveSeconds,
      sshConnectionId: sshConnectionId ?? source.sshConnectionId,
      sshConnectionName: sshConnectionName ?? source.sshConnectionName,
      container: container ?? source.container,
      image: image ?? source.image,
      service: service ?? source.service,
      composeFile: composeFile ?? source.composeFile,
      dockerContext: dockerContext ?? source.dockerContext,
    );
